### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mani1232** [Elytrium/LimboHub#1]
```
[00:29:49 WARN] [fastmotd]: Failed to load favicon example-com-server-icon.png. Ensure that the file exists or modify config.yml
[00:29:50 WARN] [fastmotd]: Failed to load favicon example-com-server-icon.png. Ensure that the file exists or modify config.yml
[00:29:50 INFO] [limboapi]: Creating and preparing packets...
[00:29:50 WARN] [limboapi]: Currently working only with 1.16 - 1.20.1 versions, modify the plugins/limboapi/config.yml file if you want the plugin to work with other versions.
[00:29:50 INFO] [limboapi]: Loaded!
[00:29:50 INFO] [limbofilter]: Current captcha generator settings will consume 0.69GB RAM normally and 1.37GB RAM on reloads
[00:29:50 INFO] [limbofilter]: Modify the config to decrease RAM consumption
[00:29:52 ERROR]: Couldn't pass ProxyInitializeEvent to limbohub
net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboapi.protocol.LimboProtocol.register(LimboProtocol.java:444) ~[?:?]
        at net.elytrium.limboapi.protocol.LimboProtocol.register(LimboProtocol.java:415) ~[?:?]
        at net.elytrium.limboapi.server.LimboImpl.registerPacket(LimboImpl.java:540) ~[?:?]
        at net.elytrium.limbohub.LimboHub.reload(LimboHub.java:355) ~[?:?]
        at net.elytrium.limbohub.LimboHub.onProxyInitialization(LimboHub.java:155) ~[?:?]
        at net.elytrium.limbohub.Lmbda$9.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) [?:?]
Caused by: net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboapi.protocol.LimboProtocol.register(LimboProtocol.java:453) ~[?:?]
        at net.elytrium.limboapi.protocol.LimboProtocol.register(LimboProtocol.java:442) ~[?:?]
        ... 11 more
Caused by: java.lang.IllegalArgumentException: Can not register class CloseContainer with id 46 for 1.8 because another packet is already registered
        at com.velocitypowered.proxy.protocol.StateRegistry$PacketRegistry.register(StateRegistry.java:513) ~[velocity-3.2.0-SNAPSHOT-260.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at net.elytrium.limboapi.protocol.LimboProtocol.register(LimboProtocol.java:451) ~[?:?]
        at net.elytrium.limboapi.protocol.LimboProtocol.register(LimboProtocol.java:442) ~[?:?]
        ... 11 more
[00:29:54 INFO] [limbofilter]: Captcha generated in 2387 ms.
[00:29:54 INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:25565
[00:29:54 INFO]: Done (7.66s)!
```

**Comment by mani1232** [comment]
> /velocity dump

```
{
  "versionInfo": {
    "name": "Velocity",
    "vendor": "Velocity Contributors",
    "version": "3.2.0-SNAPSHOT (git-37fedf50-b260)"
  },
  "platform": {
    "operatingSystemType": "Linux",
    "operatingSystemVersion": "6.1.0-10-amd64",
    "operatingSystemArchitecture": "amd64",
    "javaVersion": "20.0.1",
    "javaVendor": "GraalVM Community",
    "listener": {
      "listenerType": "epoll",
      "compression": "libdeflate (Linux x86_64)",
      "encryption": "OpenSSL 3.0.x (Linux x86_64)"
    }
  },
  "config": {
    "bind": "0.0.0.0:25565",
    "motd": "\u003c#09add3\u003eWorldMandia Proxy",
    "showMaxPlayers": 500,
    "onlineMode": false,
    "preventClientProxyConnections": false,
    "playerInfoForwardingMode": "MODERN",
    "announceForge": false,
    "onlineModeKickExistingPlayers": false,
    "pingPassthrough": "DISABLED",
    "advanced": {
      "compressionThreshold": 256,
      "compressionLevel": 9,
      "loginRatelimit": 3000,
      "connectionTimeout": 10000,
      "readTimeout": 60000,
      "proxyProtocol": true,
      "tcpFastOpen": true,
      "bungeePluginMessageChannel": true,
      "showPingRequests": false,
      "failoverOnUnexpectedServerDisconnect": true,
      "announceProxyCommands": true,
      "logCommandExecutions": false,
      "logPlayerConnections": true
    },
    "query": {
      "queryEnabled": false,
      "queryPort": 25577,
      "queryMap": "Velocity",
      "showPlugins": false
    },
    "enablePlayerAddressLogging": true,
    "forceKeyAuthentication": false,
    "servers": {
      "survival": {
        "currentPlayers": 0,
        "host": "127.0.0.1",
        "port": 30000
      }
    },
    "connectOrder": [
      "survival"
    ],
    "forcedHosts": {
      "play.worldmandia.cc": [
        "survival"
      ]
    }
  },
  "plugins": [
    {
      "id": "protocolize",
      "name": "Protocolize",
      "version": "v2",
      "authors": [
        "Exceptionflug"
      ]
    },
    {
      "id": "commandblocker",
      "name": "CommandBlocker",
      "version": "1.3.1",
      "authors": [
        "TauCubed"
      ],
      "description": "It regex. It tab. but most important, It blocc.",
      "url": "https://gitlab.com/TauCu/command-blocker",
      "dependencies": [
        "protocolize"
      ]
    },
    {
      "id": "fastmotd",
      "name": "FastMOTD",
      "version": "1.0.3",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "description": "MOTD plugin that uses FastPrepareAPI.",
      "url": "https://elytrium.net/"
    },
    {
      "id": "limboapi",
      "name": "LimboAPI",
      "version": "1.1.15",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "description": "Velocity plugin for making virtual servers.",
      "url": "https://elytrium.net/"
    },
    {
      "id": "limboauth",
      "name": "LimboAuth",
      "version": "1.1.13",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi",
        "floodgate"
      ]
    },
    {
      "id": "limbofilter",
      "name": "LimboFilter",
      "version": "1.1.11",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/",
      "dependencies": [
        "limboapi"
      ]
    },
    {
      "id": "limbohub",
      "name": "LimboHub",
      "version": "1.0.1",
      "authors": [
        "JNNGL"
      ],
      "dependencies": [
        "limboapi"
      ]
    },
    {
      "id": "limboqueue",
      "name": "LimboQueue",
      "version": "1.0.1",
      "authors": [
        "skywatcher_2019",
        "hevav"
      ]
    },
    {
      "id": "limboreconnect",
      "name": "LimboReconnect",
      "version": "1.1.1",
      "authors": [
        "SkyWatcher_2019",
        "hevav"
      ]
    },
    {
      "id": "luckperms",
      "name": "LuckPerms",
      "version": "5.4.98",
      "authors": [
        "Luck"
      ],
      "description": "A permissions plugin",
      "url": "https://luckperms.net"
    },
    {
      "id": "skinsrestorer",
      "name": "SkinsRestorer",
      "version": "15.0.0-SNAPSHOT",
      "authors": [
        "knat",
        "AlexProgrammerDE",
        "Blackfire62",
        "McLive"
      ],
      "description": "Ability to restore/change skins on servers! (Offline and Online Mode)",
      "url": "https://skinsrestorer.net",
      "dependencies": [
        "floodgate"
      ]
    },
    {
      "id": "velocity_tools",
      "name": "VelocityTools",
      "version": "1.1.9",
      "authors": [
        "Elytrium (https://elytrium.net/)"
      ],
      "url": "https://elytrium.net/"
    }
  ]
}
```
